### ISSUE TITLE
Boost Acceleration | v.0.1.6 (updated v.0.2.3)

### ISSUE THREAD

**Issue by cellaneza** [CoolCoderMan281/Road-Kill#10]
![image](https://github.com/CoolCoderMan281/Stumpy-Road/assets/123773582/87eec27a-5075-4a25-a261-983fba1518d8)
[I really suggest using this link to the Miro Board to better read it all.](https://miro.com/app/board/uXjVNSw5WwE=/)

📝 All the stuff labeled red is what needs to be added. Some of it might not seem as important (please reach out if you have any concerns), but I stress adding these parts because it's designed to make the car feel more weighted and powerful.
Here's the lowdown:
- Incorporate Acceleration Lag to emphasize weight of the car & to dissuade holding down the W/Up Arrow Key forever indefinitely.
- Add tweening for the car to build up speed into boost (rather then just automatically snap into the higher speed).

Sliders are needed for:
- Acceleration Lag (how long the player needs to hold down the W/Up Arrow Key until they start speeding up)
- Animal Acceleration (affects how fast the animals will speed up)

FINAL BOOST BUFF VALUE: 0.3

**Comment by CoolCoderMan281** [comment]
Smoothing added
