### ISSUE TITLE
Boost System Fixes | v.0.2.3

### ISSUE THREAD

**Issue by cellaneza** [CoolCoderMan281/Road-Kill#17]
📝 Final development day, let's do this! 😁 

![image](https://github.com/CoolCoderMan281/Stumpy-Road/assets/123773582/a549ca78-dd71-43dd-8966-565cafebc218)

⚙️ Implement the "W" Boost so that, when it's active, the player's left & right speed (Car Speed) is smaller (the value for car speed during boost should be "(Car Speed)/3 = 0.5". We won't have the time to test this value, we just gotta run with it! Don't make a slider for it!)
ALSO:
- make sure that the player can't boost when the player is in rage mode!
- "Up Arrow Key" should also let the player boost!
- FOV should transition to 65 when player boosts.

**Comment by CoolCoderMan281** [comment]
Done
